theme: jekyll-theme-midnight
title: amimashifa-projects-homepage
description: Hola! I'm Amima Shifa this site contains a glimpse of my journey as a freelance software developer. Feel free to bookmark this to keep an eye on my project updates.
